# Generated by Django 4.1.7 on 2023-05-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_semester_term_calendarsemester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarcourse',
            name='semester',
        ),
        migrations.AddField(
            model_name='calendarcourse',
            name='calendarSemester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.calendarsemester'),
        ),
    ]
