# Generated by Django 4.1.7 on 2023-05-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_calendarcourse_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='term',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Winter', 'Winter'), ('Summer', 'Summer')], max_length=10),
        ),
    ]
