# Generated by Django 4.1.7 on 2023-06-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_semester_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarcourse',
            name='onCalendar',
            field=models.BooleanField(null=True),
        ),
    ]
