# Generated by Django 4.1.7 on 2023-06-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_online', models.BooleanField(default=False)),
                ('is_open_to_public', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=1000, null=True)),
                ('location', models.CharField(max_length=1000, null=True)),
                ('board', models.ManyToManyField(related_name='board_professors', to='professor.professor')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervisor_professor', to='professor.professor')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('dissertation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dissertation.dissertation')),
            ],
        ),
    ]
