# Generated by Django 4.1.7 on 2023-06-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_enrolledstudentsoncalendarcourse_oncalendar'),
        ('dissertation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dissertation',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.student'),
        ),
    ]
