# Generated by Django 5.0.1 on 2024-01-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0002_dissertation_is_approved_dissertation_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardissertation',
            name='onCalendar',
            field=models.BooleanField(null=True),
        ),
    ]
