# Generated by Django 4.1.7 on 2023-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_event_course_remove_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
