# Generated by Django 4.1.7 on 2023-05-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_change_event_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
