# Generated by Django 4.1.7 on 2023-06-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_rename_approved_change_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='change',
        ),
        migrations.AddField(
            model_name='event',
            name='changes',
            field=models.ManyToManyField(to='event.change'),
        ),
    ]
