# Generated by Django 4.1.7 on 2023-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_remove_event_change_event_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='day',
        ),
        migrations.AddField(
            model_name='change',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='change',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
