# Generated by Django 4.1.7 on 2023-06-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_remove_change_day_change_date_change_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
