# Generated by Django 5.0.1 on 2024-01-27 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0003_calendardissertation_oncalendar'),
        ('event', '0014_event_calendarseminar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendarDissertation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dissertation.calendardissertation'),
        ),
    ]
