# Generated by Django 5.0.1 on 2024-01-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_event_calendardissertation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
