# Generated by Django 4.1.7 on 2023-06-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('is_online', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=1000, null=True)),
                ('speaker_fullname', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarSeminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seminar.seminar')),
            ],
        ),
    ]
