# Generated by Django 4.1.7 on 2023-06-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_enrolledstudentsoncalendarcourse_oncalendar'),
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledStudentToCalendarSeminars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onCalendar', models.BooleanField()),
                ('calendarSeminar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seminar.calendarseminar')),
                ('students', models.ManyToManyField(to='student.student')),
            ],
        ),
    ]
