# Generated by Django 4.1.7 on 2023-06-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_enrolledstudenttocalendarseminars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledstudenttocalendarseminars',
            name='onCalendar',
        ),
        migrations.AddField(
            model_name='calendarseminar',
            name='onCalendar',
            field=models.BooleanField(null=True),
        ),
    ]
